// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService 提供与运行平台相关的信息，暴露给前端用于平台差异化渲染。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckForUpdates 供前端调用（如设置-关于页的「检查更新」按钮），触发与菜单
 * 「Check for Updates…」相同的更新流程：弹出 Software Update 窗口 + 只做检查。
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(3236035852);
}

/**
 * CheckForUpdatesSilent 供前端在启动时调用，触发静默更新检查（后台运行，不弹窗）。
 * 若有新版本可用，会通过 "clip:update:available" 事件通知前端。
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdatesSilent() {
    return $Call.ByID(3958633237);
}

/**
 * DownloadImage 下载图片到用户指定的目录：弹出保存对话框选择位置后写盘。
 * 
 * referer 是文章源站地址：正文图片普遍有防盗链（空 Referer 直接 403），
 * 下载与正文渲染必须带同一条 Referer，否则点「下载」会以「下载失败」告终。
 * 
 * 返回 (true, nil) 表示已保存；(false, nil) 表示用户取消；(false, err) 表示失败。
 * 文件名从 URL 路径推断，无法推断时回退为 "image"；扩展名缺失时按 Content-Type 补全。
 * @param {string} rawURL
 * @param {string} referer
 * @returns {$CancellablePromise<boolean>}
 */
export function DownloadImage(rawURL, referer) {
    return $Call.ByID(2976514266, rawURL, referer);
}

/**
 * FetchChangelog 返回更新日志原始 Markdown 文本，供前端渲染。
 * 
 * 优先读本地缓存：changelogURL 指向仓库 main 分支，内容就是「最新已发布版本」的日志，
 * 所以当版本号与缓存一致、且更新检查已确认无新版时，远端内容不可能变，直接复用即可，
 * 不再发请求。检出新版（或尚未检查）时缓存立即失效，保证升级前后都能看到对应的日志。
 * 
 * 抓取失败时若存有本版本的缓存则回退返回缓存，让离线状态下仍能查看更新日志。
 * @returns {$CancellablePromise<string>}
 */
export function FetchChangelog() {
    return $Call.ByID(3553216659);
}

/**
 * IsOnline 探测网络连通性，返回 true 表示在线，false 表示离线。
 * 
 * 实现方式：尝试连接 Google Public DNS (8.8.8.8:53)，超时 2 秒。
 * 该方法简单快速，但无法区分"本地网络正常但外网不通"的情况。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsOnline() {
    return $Call.ByID(4195382262);
}

/**
 * Platform 返回当前运行的操作系统标识。
 * 
 * 仅区分本项目支持的两个桌面平台：
 *   - "mac"     — macOS（runtime.GOOS == "darwin"）
 *   - "windows" — Windows 及其它
 * @returns {$CancellablePromise<string>}
 */
export function Platform() {
    return $Call.ByID(2821667470);
}

/**
 * SetFocusMode 由前端在进入/退出专注阅读模式时调用：前端 chrome 由 CSS 隐藏，
 * 原生菜单栏只存在于 GTK/系统层，交给 main 注入的回调处理。
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetFocusMode(enabled) {
    return $Call.ByID(2704993486, enabled);
}

/**
 * SetOnline 接收前端 navigator.onLine 变化并同步后台网络模式。
 * @param {boolean} online
 * @returns {$CancellablePromise<void>}
 */
export function SetOnline(online) {
    return $Call.ByID(243765160, online);
}

/**
 * SetTheme 在非 Windows 平台上是空操作。
 * 
 * macOS 使用隐藏式标题栏（MacTitleBarHiddenInset），无需切换原生主题。
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(mode) {
    return $Call.ByID(1434316160, mode);
}

/**
 * Version 返回当前应用版本号，供设置-关于页展示。
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(4285456131);
}
