// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CacheStats 缓存统计：可清理的文章条数及预计可释放空间（字节）。
 */
export class CacheStats {
    /**
     * Creates a new CacheStats instance.
     * @param {Partial<CacheStats>} [$$source = {}] - The source object to create the CacheStats.
     */
    constructor($$source = {}) {
        if (!("cacheCount" in $$source)) {
            /**
             * 可清理文章数（已读且未星标）
             * @member
             * @type {number}
             */
            this["cacheCount"] = 0;
        }
        if (!("estimatedBytes" in $$source)) {
            /**
             * 预计可释放字节数
             * @member
             * @type {number}
             */
            this["estimatedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CacheStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheStats(/** @type {Partial<CacheStats>} */($$parsedSource));
    }
}

/**
 * Category 订阅源分类（支持树形结构）
 */
export class Category {
    /**
     * Creates a new Category instance.
     * @param {Partial<Category>} [$$source = {}] - The source object to create the Category.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * null 表示根分类
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 排序权重
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Category}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category(/** @type {Partial<Category>} */($$parsedSource));
    }
}

/**
 * CategoryWithFeeds 分类附带订阅源列表
 */
export class CategoryWithFeeds {
    /**
     * Creates a new CategoryWithFeeds instance.
     * @param {Partial<CategoryWithFeeds>} [$$source = {}] - The source object to create the CategoryWithFeeds.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * null 表示根分类
             * @member
             * @type {number | null}
             */
            this["parentId"] = null;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 排序权重
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("feeds" in $$source)) {
            /**
             * @member
             * @type {FeedWithUnread[]}
             */
            this["feeds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryWithFeeds instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CategoryWithFeeds}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("feeds" in $$parsedSource) {
            $$parsedSource["feeds"] = $$createField6_0($$parsedSource["feeds"]);
        }
        return new CategoryWithFeeds(/** @type {Partial<CategoryWithFeeds>} */($$parsedSource));
    }
}

/**
 * Feed RSS/Atom 订阅源
 */
export class Feed {
    /**
     * Creates a new Feed instance.
     * @param {Partial<Feed>} [$$source = {}] - The source object to create the Feed.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * 可选分类
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（分钟）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("maxItems" in $$source)) {
            /**
             * 最大保留条目数
             * @member
             * @type {number}
             */
            this["maxItems"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["lastUpdated"] = null;
        }
        if (!("errorCount" in $$source)) {
            /**
             * 连续错误次数
             * @member
             * @type {number}
             */
            this["errorCount"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {string | null}
             */
            this["lastError"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * active/paused/error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Feed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Feed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Feed(/** @type {Partial<Feed>} */($$parsedSource));
    }
}

/**
 * FeedWithUnread Feed 附带未读计数
 */
export class FeedWithUnread {
    /**
     * Creates a new FeedWithUnread instance.
     * @param {Partial<FeedWithUnread>} [$$source = {}] - The source object to create the FeedWithUnread.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("link" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["link"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * favicon URL
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("categoryId" in $$source)) {
            /**
             * 可选分类
             * @member
             * @type {number | null}
             */
            this["categoryId"] = null;
        }
        if (!("updateInterval" in $$source)) {
            /**
             * 更新间隔（分钟）
             * @member
             * @type {number}
             */
            this["updateInterval"] = 0;
        }
        if (!("maxItems" in $$source)) {
            /**
             * 最大保留条目数
             * @member
             * @type {number}
             */
            this["maxItems"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["lastUpdated"] = null;
        }
        if (!("errorCount" in $$source)) {
            /**
             * 连续错误次数
             * @member
             * @type {number}
             */
            this["errorCount"] = 0;
        }
        if (!("lastError" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {string | null}
             */
            this["lastError"] = null;
        }
        if (!("status" in $$source)) {
            /**
             * active/paused/error
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeedWithUnread instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeedWithUnread}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeedWithUnread(/** @type {Partial<FeedWithUnread>} */($$parsedSource));
    }
}

/**
 * Item RSS 文章条目
 */
export class Item {
    /**
     * Creates a new Item instance.
     * @param {Partial<Item>} [$$source = {}] - The source object to create the Item.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["publishedAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["updatedAt"] = null;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * RSS 给的正文（可能只是摘要）
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("fullContent" in $$source)) {
            /**
             * FullContent 是按需从原文页面提取的正文。空串表示尚未提取。
             * 与 Content 并存：提取结果不覆盖 RSS 原文，抓错了可以回退。
             * @member
             * @type {string}
             */
            this["fullContent"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * 摘要
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("enclosure" in $$source)) {
            /**
             * 附件 URL（音频/视频）
             * @member
             * @type {string}
             */
            this["enclosure"] = "";
        }
        if (!("categories" in $$source)) {
            /**
             * JSON 数组字符串
             * @member
             * @type {string}
             */
            this["categories"] = "";
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("readAt" in $$source)) {
            /**
             * 可为 NULL
             * @member
             * @type {time$0.Time | null}
             */
            this["readAt"] = null;
        }
        if (!("note" in $$source)) {
            /**
             * 用户笔记
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Item}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item(/** @type {Partial<Item>} */($$parsedSource));
    }
}

/**
 * ItemLight 文章条目轻量版本（不含 content 字段，用于列表视图）
 */
export class ItemLight {
    /**
     * Creates a new ItemLight instance.
     * @param {Partial<ItemLight>} [$$source = {}] - The source object to create the ItemLight.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("feedId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["feedId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["publishedAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["updatedAt"] = null;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("enclosure" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enclosure"] = "";
        }
        if (!("categories" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["categories"] = "";
        }
        if (!("isRead" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isRead"] = false;
        }
        if (!("isStarred" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStarred"] = false;
        }
        if (!("readAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["readAt"] = null;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemLight instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ItemLight}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemLight(/** @type {Partial<ItemLight>} */($$parsedSource));
    }
}

/**
 * Settings 应用全局设置。
 * 
 * ⚠️ 所有字段必须是标量类型：本结构体依赖 Go 的可比较性（测试与变更检测均用 ==
 * 直接比较整个结构体）。加入 slice / map / 函数字段会使其不可比较，编译期即失败。
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * system / light / dark / sepia
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * zh / zh-TW / en
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("defaultUpdateInterval" in $$source)) {
            /**
             * 全局更新间隔（分钟；字段名为兼容旧设置保留）
             * @member
             * @type {number}
             */
            this["defaultUpdateInterval"] = 0;
        }
        if (!("defaultMaxItems" in $$source)) {
            /**
             * 默认每源最大保留条目数
             * @member
             * @type {number}
             */
            this["defaultMaxItems"] = 0;
        }
        if (!("notificationMode" in $$source)) {
            /**
             * each / summary / off
             * @member
             * @type {string}
             */
            this["notificationMode"] = "";
        }
        if (!("showUnreadBadge" in $$source)) {
            /**
             * 是否展示未读角标：macOS 在 Dock 显示数字，Windows 在任务栏显示红点
             * @member
             * @type {boolean}
             */
            this["showUnreadBadge"] = false;
        }
        if (!("autoMarkReadDelay" in $$source)) {
            /**
             * 自动标记已读延迟（毫秒）：-1 关闭 / 0 立即 / >0 延迟
             * @member
             * @type {number}
             */
            this["autoMarkReadDelay"] = 0;
        }
        if (!("reduceMotion" in $$source)) {
            /**
             * 减弱动画效果（无障碍）
             * @member
             * @type {boolean}
             */
            this["reduceMotion"] = false;
        }
        if (!("showFocusIndicator" in $$source)) {
            /**
             * 显示焦点指示器（无障碍）
             * @member
             * @type {boolean}
             */
            this["showFocusIndicator"] = false;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * 主窗口上次关闭时的宽度
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * 主窗口上次关闭时的高度
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("proxyHost" in $$source)) {
            /**
             * HTTP 代理 IP / 主机名
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * HTTP 代理端口
             * @member
             * @type {number}
             */
            this["proxyPort"] = 0;
        }
        if (!("readerFontFamily" in $$source)) {
            /**
             * 阅读视图排版偏好。原先存于前端 localStorage（clip-reader），
             * 收归后端以便随配置一起备份同步。
             * sans / serif / mono
             * @member
             * @type {string}
             */
            this["readerFontFamily"] = "";
        }
        if (!("readerFontSize" in $$source)) {
            /**
             * 14 / 16 / 18
             * @member
             * @type {number}
             */
            this["readerFontSize"] = 0;
        }
        if (!("readerLineHeight" in $$source)) {
            /**
             * 1.5 / 1.8 / 2.0
             * @member
             * @type {number}
             */
            this["readerLineHeight"] = 0;
        }
        if (!("readerWidth" in $$source)) {
            /**
             * 640 / 800 / full
             * @member
             * @type {string}
             */
            this["readerWidth"] = "";
        }
        if (!("readerBackground" in $$source)) {
            /**
             * default / light / sepia / dark
             * @member
             * @type {string}
             */
            this["readerBackground"] = "";
        }
        if (!("readerShowSummary" in $$source)) {
            /**
             * ReaderShowSummary 阅读器正文模式：true 优先显示 RSS 摘要，false 优先显示提取的全文。
             * 持久化为用户偏好：切换文章、重启都沿用上一次的选择。
             * @member
             * @type {boolean}
             */
            this["readerShowSummary"] = false;
        }
        if (!("menuBarVisible" in $$source)) {
            /**
             * MenuBarVisible 原生菜单栏是否可见（View 菜单「隐藏/显示菜单」的用户偏好）。
             * F11 全屏与专注模式属于临时隐藏，退出时恢复到这个值，而不是无条件显示。
             * @member
             * @type {boolean}
             */
            this["menuBarVisible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FeedWithUnread.createFrom;
const $$createType1 = $Create.Array($$createType0);
